
services:
  php-env:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 9010:80
    depends_on:
      - db


      
  db:
    image: mysql:8.3.0
    ports:
      - '9008:80'
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    env_file:
      - .env
    ports:
      - '9005:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
volumes:
  db-data: